variables:
  BUILD_AGENT: $CI_REGISTRY/bkappz/build-agents
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  CARGO_TERM_COLOR: always

default:
  tags:
    - linux
  cache:
    key:
      files:
        - Cargo.lock
        - proc-macro/Cargo.lock
      prefix: cargo-$CI_JOB_IMAGE
    paths:
      - .cargo/registry/index/
      - .cargo/registry/cache/
      - .cargo/git/db/
      - .cargo/git/checkouts/
    policy: pull-push

stages:
  - build
  - deploy

rust::latest:
  stage: build
  image: $BUILD_AGENT/rust:latest
  parallel:
    matrix:
      - FEATURE_NAME: "no-default"
        FEATURE_FLAGS: "--no-default-features"
      - FEATURE_NAME: "serde"
        FEATURE_FLAGS: "--no-default-features --features serde"
      - FEATURE_NAME: "std"
        FEATURE_FLAGS: "--no-default-features --features std"
      - FEATURE_NAME: "std-serde"
        FEATURE_FLAGS: "--no-default-features --features std --features serde"
  coverage: '/TOTAL\s+(\d+\s+)+(\d+\.\d+\%)/'
  script:
    - "echo \"Running feature set: $FEATURE_NAME ($FEATURE_FLAGS)\""
    - cargo build $FEATURE_FLAGS --verbose
    - cargo llvm-cov nextest --color=always $FEATURE_FLAGS
    - cargo llvm-cov report --cobertura --output-path target/llvm-cov-target/cobertura.xml
  artifacts:
    reports:
      junit: target/nextest/default/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: target/llvm-cov-target/cobertura.xml

rust::nightly:
  stage: build
  image: rustlang/rust:nightly
  parallel:
    matrix:
      - FEATURE_NAME: "no-default"
        FEATURE_FLAGS: "--no-default-features"
      - FEATURE_NAME: "serde"
        FEATURE_FLAGS: "--no-default-features --features serde"
      - FEATURE_NAME: "std"
        FEATURE_FLAGS: "--no-default-features --features std"
      - FEATURE_NAME: "std-serde"
        FEATURE_FLAGS: "--no-default-features --features std --features serde"
  script:
    - "echo \"Running feature set: $FEATURE_NAME ($FEATURE_FLAGS)\""
    - cargo build $FEATURE_FLAGS --verbose
    - cargo test $FEATURE_FLAGS --verbose
  allow_failure: true

pages:
  stage: deploy
  image: $BUILD_AGENT/rust:latest
  script:
    - cargo doc --no-deps --no-default-features --features "std serde" -p figen
    - rm -rf public
    - mkdir -p public
    - cp -r target/doc/* public/
    - printf '<meta http-equiv="refresh" content="0; url=figen/index.html">' > public/index.html
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
